import { readdir, stat } from "node:fs/promises";
import { join } from "path";

const SKILLS_ROOT = join(import.meta.dir, "..");

function formatRule(content: string, filename: string): string {
  const titleMatch = content.match(/title:\s*(.*)/);
  const title = titleMatch ? titleMatch[1].trim() : filename.replace(".md", "");
  const body = content.replace(/---[\s\S]*?---/, "").trim();

  return `\n### RULE: ${title}\n(File: ${filename})\n\n${body}\n`;
}

async function buildSkillSet(techName: string) {
  const rulesDir = join(SKILLS_ROOT, techName, "rules");
  const outputFile = join(SKILLS_ROOT, techName, "SKILL.md");

  try {
    const stats = await stat(rulesDir);
    if (!stats.isDirectory()) return;
  } catch {
    return;
  }

  console.log(`Building Skill: ${techName.toUpperCase()}`);

  const files = await readdir(rulesDir);
  const mdFiles = files.filter((f) => f.endsWith(".md")).sort();

  if (mdFiles.length === 0) {
    console.log(`No rules found in ${techName}/rules`);
    return;
  }

  let outputContent = `# SKILL SET: ${techName.toUpperCase()}\n`;
  outputContent += `> AUTO-GENERATED by Axel Mrak Build System.\n`;
  outputContent += `> Updated: ${new Date().toISOString().split("T")[0]}\n`;
  outputContent += `> Contains ${mdFiles.length} architectural rules.\n\n`;

  for (const filename of mdFiles) {
    const content = await Bun.file(join(rulesDir, filename)).text();
    outputContent += formatRule(content, filename);
  }

  await Bun.write(outputFile, outputContent);
  console.log(`Generated: ${techName}/SKILL.md`);
}

console.log("Starting Axel Mrak Skills Build...");
const folders = await readdir(SKILLS_ROOT);

for (const folder of folders) {
  if (!folder.startsWith("_") && !folder.startsWith(".")) {
    const folderPath = join(SKILLS_ROOT, folder);
    try {
      const stats = await stat(folderPath);
      if (stats.isDirectory()) {
        await buildSkillSet(folder);
      }
    } catch {}
  }
}
console.log("Build complete.");
