import { readdir, stat } from "node:fs/promises";
import { join } from "path";

const SKILLS_ROOT = join(import.meta.dir, "..");

function formatRule(content: string, filename: string): string {
  const titleMatch = content.match(/title:\s*(.*)/);
  const title = titleMatch ? titleMatch[1].trim() : filename.replace(".md", "");
  const body = content.replace(/---[\s\S]*?---/, "").trim();

  return `\n### RULE: ${title}\n(File: ${filename})\n\n${body}\n`;
}

async function buildSkillSet(techName: string) {
  const rulesDir = join(SKILLS_ROOT, techName, "rules");

  try {
    const stats = await stat(rulesDir);
    if (!stats.isDirectory()) return;
  } catch {
    return;
  }

  console.log(`Building Skill: ${techName.toUpperCase()}`);

  const files = await readdir(rulesDir);
  const mdFiles = files.filter((f) => f.endsWith(".md")).sort();

  if (mdFiles.length === 0) {
    console.log(`No rules found in ${techName}/rules`);
    return;
  }

  // Group files by prefix (before first dash)
  const groups: Record<string, string[]> = {};
  for (const filename of mdFiles) {
    const prefix = filename.split('-')[0];
    if (!groups[prefix]) groups[prefix] = [];
    groups[prefix].push(filename);
  }

  // Generate separate SKILL.md files for each group
  for (const [prefix, groupFiles] of Object.entries(groups)) {
    if (prefix.startsWith('_')) continue; // Skip special files like _sections.md

    let outputContent = `# SKILL SET: ${techName.toUpperCase()} - ${prefix.toUpperCase()}\n`;
    outputContent += `> AUTO-GENERATED by Axel Mrak Build System.\n`;
    outputContent += `> Updated: ${new Date().toISOString().split("T")[0]}\n`;
    outputContent += `> Contains ${groupFiles.length} architectural rules.\n\n`;

    for (const filename of groupFiles) {
      const content = await Bun.file(join(rulesDir, filename)).text();
      outputContent += formatRule(content, filename);
    }

    const outputFile = join(SKILLS_ROOT, techName, `${prefix}-rules.md`);
    await Bun.write(outputFile, outputContent);
    console.log(`Generated: ${techName}/${prefix}-rules.md`);
  }

  // Also generate the main SKILL.md for backward compatibility (but smaller)
  let mainOutputContent = `# SKILL SET: ${techName.toUpperCase()}\n`;
  mainOutputContent += `> AUTO-GENERATED by Axel Mrak Build System.\n`;
  mainOutputContent += `> Updated: ${new Date().toISOString().split("T")[0]}\n`;
  mainOutputContent += `> Contains ${mdFiles.length} architectural rules across ${Object.keys(groups).filter(g => !g.startsWith('_')).length} modules.\n\n`;
  mainOutputContent += `## Available Modules\n\n`;
  for (const [prefix, groupFiles] of Object.entries(groups)) {
    if (prefix.startsWith('_')) continue;
    mainOutputContent += `- **${prefix}-rules.md**: ${groupFiles.length} rules\n`;
  }

  const mainOutputFile = join(SKILLS_ROOT, techName, "SKILL.md");
  await Bun.write(mainOutputFile, mainOutputContent);
  console.log(`Generated: ${techName}/SKILL.md`);
}

console.log("Starting Axel Mrak Skills Build...");
const folders = await readdir(SKILLS_ROOT);

for (const folder of folders) {
  if (!folder.startsWith("_") && !folder.startsWith(".")) {
    const folderPath = join(SKILLS_ROOT, folder);
    try {
      const stats = await stat(folderPath);
      if (stats.isDirectory()) {
        await buildSkillSet(folder);
      }
    } catch {}
  }
}
console.log("Build complete.");